

export default function ButtonColors() {
  return (
    <div
      dangerouslySetInnerHTML={{
        __html: `<div class="flex flex-wrap justify-center gap-4"><button data-ripple-light="true" class="inline-flex select-none items-center justify-center rounded-md border border-slate-800 bg-slate-800 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-slate-50 transition-all duration-300 ease-in hover:border-slate-700 hover:bg-slate-700 disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Primary</button><button data-ripple-dark="true" class="inline-flex select-none items-center justify-center rounded-md border border-slate-200 bg-slate-200 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-slate-800 transition-all duration-300 ease-in hover:bg-slate-100 hover:bg-slate-100 disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Secondary</button><button data-ripple-light="true" class="inline-flex select-none items-center justify-center rounded-md border border-blue-500 bg-blue-500 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-blue-50 transition-all duration-300 ease-in hover:border-info-light hover:bg-info-light disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Info</button><button data-ripple-light="true" class="inline-flex select-none items-center justify-center rounded-md border border-green-500 bg-green-500 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-green-50 transition-all duration-300 ease-in hover:border-success-light hover:bg-success-light disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Success</button><button data-ripple-light="true" class="inline-flex select-none items-center justify-center rounded-md border border-amber-500 bg-amber-500 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-amber-50 transition-all duration-300 ease-in hover:border-warning-light hover:bg-warning-light disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Warning</button><button data-ripple-light="true" class="inline-flex select-none items-center justify-center rounded-md border border-red-500 bg-red-500 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-red-50 transition-all duration-300 ease-in hover:border-error-light hover:bg-error-light disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Error</button></div>
`
      }}
    />
  );
}
