
export default function SelectColors() {
  return (
    <div
      dangerouslySetInnerHTML={{
        __html: `<div class="flex w-72 flex-col items-center gap-4"><button tabindex="0" type="button" class="flex items-center gap-4 justify-between h-max w-full outline-none focus:outline-none text-slate-600 bg-transparent ring-transparent border border-slate-200 transition-all duration-300 ease-in disabled:opacity-50 disabled:pointer-events-none data-[error=true]:border-error data-[success=true]:border-success select-none text-start data-[shape=pill]:rounded-full [&amp;_data-slot=placeholder]:text-foreground/60 text-sm rounded-md py-2 px-2.5 ring shadow-sm hover:border-slate-800 hover:ring-slate-800/10 focus:border-slate-800 focus:ring-slate-800/10 data-[open=true]:border-primary data-[open=true]:ring-primary/10" data-open="false" data-error="false" data-success="false" aria-expanded="false" aria-haspopup="listbox" role="combobox"><span data-slot="placeholder">Color. e.g. primary</span><svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" color="currentColor" class="h-[1em] w-[1em] translate-x-0.5 stroke-[1.5]">
      <path d="M17 8L12 3L7 8" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
      <path d="M17 16L12 21L7 16" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
    </svg></button><input readonly="" style="display:none" value="" /><button tabindex="0" type="button" class="flex items-center gap-4 justify-between h-max w-full outline-none focus:outline-none text-slate-600 bg-transparent ring-transparent border border-slate-200 transition-all duration-300 ease-in disabled:opacity-50 disabled:pointer-events-none data-[error=true]:border-error data-[success=true]:border-success select-none text-start data-[shape=pill]:rounded-full [&amp;_data-slot=placeholder]:text-foreground/60 text-sm rounded-md py-2 px-2.5 ring shadow-sm hover:border-slate-500 hover:ring-secondary/10 focus:border-secondary focus:ring-secondary/10 data-[open=true]:border-secondary data-[open=true]:ring-secondary/10" data-open="false" data-error="false" data-success="false" aria-expanded="false" aria-haspopup="listbox" role="combobox"><span data-slot="placeholder">Color. e.g. secondary</span><svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" color="currentColor" class="h-[1em] w-[1em] translate-x-0.5 stroke-[1.5]">
      <path d="M17 8L12 3L7 8" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
      <path d="M17 16L12 21L7 16" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
    </svg></button><input readonly="" style="display:none" value="" /><button tabindex="0" type="button" class="flex items-center gap-4 justify-between h-max w-full outline-none focus:outline-none text-slate-600 bg-transparent ring-transparent border border-slate-200 transition-all duration-300 ease-in disabled:opacity-50 disabled:pointer-events-none data-[error=true]:border-error data-[success=true]:border-success select-none text-start data-[shape=pill]:rounded-full [&amp;_data-slot=placeholder]:text-foreground/60 text-sm rounded-md py-2 px-2.5 ring shadow-sm hover:border-info hover:ring-info/10 focus:border-info focus:ring-info/10 data-[open=true]:border-info data-[open=true]:ring-info/10" data-open="false" data-error="false" data-success="false" aria-expanded="false" aria-haspopup="listbox" role="combobox"><span data-slot="placeholder">Color. e.g. info</span><svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" color="currentColor" class="h-[1em] w-[1em] translate-x-0.5 stroke-[1.5]">
      <path d="M17 8L12 3L7 8" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
      <path d="M17 16L12 21L7 16" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
    </svg></button><input readonly="" style="display:none" value="" /><button tabindex="0" type="button" class="flex items-center gap-4 justify-between h-max w-full outline-none focus:outline-none text-slate-600 bg-transparent ring-transparent border border-slate-200 transition-all duration-300 ease-in disabled:opacity-50 disabled:pointer-events-none data-[error=true]:border-error data-[success=true]:border-success select-none text-start data-[shape=pill]:rounded-full [&amp;_data-slot=placeholder]:text-foreground/60 text-sm rounded-md py-2 px-2.5 ring shadow-sm hover:border-success hover:ring-success/10 focus:border-success focus:ring-success/10 data-[open=true]:border-success data-[open=true]:ring-success/10" data-open="false" data-error="false" data-success="false" aria-expanded="false" aria-haspopup="listbox" role="combobox"><span data-slot="placeholder">Color. e.g. success</span><svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" color="currentColor" class="h-[1em] w-[1em] translate-x-0.5 stroke-[1.5]">
      <path d="M17 8L12 3L7 8" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
      <path d="M17 16L12 21L7 16" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
    </svg></button><input readonly="" style="display:none" value="" /><button tabindex="0" type="button" class="flex items-center gap-4 justify-between h-max w-full outline-none focus:outline-none text-slate-600 bg-transparent ring-transparent border border-slate-200 transition-all duration-300 ease-in disabled:opacity-50 disabled:pointer-events-none data-[error=true]:border-error data-[success=true]:border-success select-none text-start data-[shape=pill]:rounded-full [&amp;_data-slot=placeholder]:text-foreground/60 text-sm rounded-md py-2 px-2.5 ring shadow-sm hover:border-warning hover:ring-warning/10 focus:border-warning focus:ring-warning/10 data-[open=true]:border-warning data-[open=true]:ring-warning/10" data-open="false" data-error="false" data-success="false" aria-expanded="false" aria-haspopup="listbox" role="combobox"><span data-slot="placeholder">Color. e.g. warning</span><svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" color="currentColor" class="h-[1em] w-[1em] translate-x-0.5 stroke-[1.5]">
      <path d="M17 8L12 3L7 8" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
      <path d="M17 16L12 21L7 16" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
    </svg></button><input readonly="" style="display:none" value="" /><button tabindex="0" type="button" class="flex items-center gap-4 justify-between h-max w-full outline-none focus:outline-none text-slate-600 bg-transparent ring-transparent border border-slate-200 transition-all duration-300 ease-in disabled:opacity-50 disabled:pointer-events-none data-[error=true]:border-error data-[success=true]:border-success select-none text-start data-[shape=pill]:rounded-full [&amp;_data-slot=placeholder]:text-foreground/60 text-sm rounded-md py-2 px-2.5 ring shadow-sm hover:border-error hover:ring-error/10 focus:border-error focus:ring-error/10 data-[open=true]:border-error data-[open=true]:ring-error/10" data-open="false" data-error="false" data-success="false" aria-expanded="false" aria-haspopup="listbox" role="combobox"><span data-slot="placeholder">Color. e.g. error</span><svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" color="currentColor" class="h-[1em] w-[1em] translate-x-0.5 stroke-[1.5]">
      <path d="M17 8L12 3L7 8" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
      <path d="M17 16L12 21L7 16" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></path>
    </svg></button><input readonly="" style="display:none" value="" /></div>
`
      }}
    />
  );
}
