export const routes = [
  {
    name: "guide",
    icon: "fas fa-book",
    pages: ["installation", "license", "what-is-tailwind-css"],
  },
  {
    name: "Customization",
    icon: "fas fa-paint-brush",
    pages: ["theming", "colors", "fonts", "shadows", "screens"],
  },
  {
    name: "components",
    icon: "fas fa-shapes",
    pages: [
      "accordion",
      "alert",
      "avatar",
      "breadcrumbs",
      "button",
      "button-group",
      "card",
      "checkbox",
      "chip",
      "collapse",
      "dialog",
      "icon-button",
      "input",
      "form",
      "list",
      "menu",
      "navbar",
      "popover",
      "progress-bar",
      "radio-button",
      "select",
      "switch",
      "tabs",
      "textarea",
      "tooltip",
      "typography",
    ],
  },
];
