

export default function BlockLevelButtonGroup() {
  return (
    <div
      dangerouslySetInnerHTML={{
        __html: `<div class="flex w-full flex-col gap-4">
  <div class="inline-flex w-full flex-row"><button data-ripple-dark="true" class="inline-flex w-full select-none items-center justify-center rounded-md border border-transparent bg-transparent px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-slate-800 transition-all duration-300 ease-in hover:border-slate-800/5 hover:bg-slate-800/5 disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">React</button><button data-ripple-dark="true" class="inline-flex w-full select-none items-center justify-center rounded-md border border-transparent bg-transparent px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-slate-800 transition-all duration-300 ease-in hover:border-slate-800/5 hover:bg-slate-800/5 disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Vue</button><button data-ripple-dark="true" class="inline-flex w-full select-none items-center justify-center rounded-md border border-transparent bg-transparent px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-slate-800 transition-all duration-300 ease-in hover:border-slate-800/5 hover:bg-slate-800/5 disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Svelte</button></div>
  <div class="inline-flex w-full flex-row"><button data-ripple-light="true" class="inline-flex w-full select-none items-center justify-center rounded-md rounded-r-none border border-slate-800 bg-transparent px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-slate-800 transition-all duration-300 ease-in hover:bg-primary hover:text-primary-foreground disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">React</button><button data-ripple-light="true" class="inline-flex w-full select-none items-center justify-center rounded-none border border-l-0 border-slate-800 bg-transparent px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-slate-800 transition-all duration-300 ease-in hover:bg-primary hover:text-primary-foreground disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Vue</button><button data-ripple-light="true" class="inline-flex w-full select-none items-center justify-center rounded-md rounded-l-none border border-l-0 border-slate-800 bg-transparent px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-slate-800 transition-all duration-300 ease-in hover:bg-primary hover:text-primary-foreground disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Svelte</button></div>
  <div class="inline-flex w-full flex-row"><button data-ripple-light="true" class="inline-flex w-full select-none items-center justify-center rounded-md rounded-r-none border border-slate-800 bg-slate-800 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-slate-50 transition-all duration-300 ease-in hover:border-slate-700 hover:bg-slate-700 disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">React</button><button data-ripple-light="true" class="inline-flex w-full select-none items-center justify-center rounded-none border border-l-0 border-slate-800 bg-slate-800 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-slate-50 transition-all duration-300 ease-in hover:border-slate-700 hover:bg-slate-700 disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Vue</button><button data-ripple-light="true" class="inline-flex w-full select-none items-center justify-center rounded-md rounded-l-none border border-l-0 border-slate-800 bg-slate-800 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-slate-50 transition-all duration-300 ease-in hover:border-slate-700 hover:bg-slate-700 disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Svelte</button></div>
  <div class="inline-flex w-full flex-row"><button data-ripple-light="true" class="inline-flex w-full select-none items-center justify-center rounded-md rounded-r-none border border-slate-800 bg-gradient-to-tr from-primary-dark to-primary-light px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-slate-50 transition-all duration-300 ease-in hover:brightness-105 disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">React</button><button data-ripple-light="true" class="inline-flex w-full select-none items-center justify-center rounded-none border border-l-0 border-slate-800 bg-gradient-to-tr from-primary-dark to-primary-light px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-slate-50 transition-all duration-300 ease-in hover:brightness-105 disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Vue</button><button data-ripple-light="true" class="inline-flex w-full select-none items-center justify-center rounded-md rounded-l-none border border-l-0 border-slate-800 bg-gradient-to-tr from-primary-dark to-primary-light px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-slate-50 transition-all duration-300 ease-in hover:brightness-105 disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Svelte</button></div>
</div>
`
      }}
    />
  );
}
