

export default function ButtonGroupColors() {
  return (
    <div
      dangerouslySetInnerHTML={{
        __html: `<div class="flex flex-col gap-4">
  <div class="inline-flex flex-row"><button data-ripple-light="true" class="inline-flex select-none items-center justify-center rounded-md rounded-r-none border border-slate-800 bg-slate-800 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-slate-50 transition-all duration-300 ease-in hover:border-slate-700 hover:bg-slate-700 disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">React</button><button data-ripple-light="true" class="inline-flex select-none items-center justify-center rounded-none border border-l-0 border-slate-800 bg-slate-800 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-slate-50 transition-all duration-300 ease-in hover:border-slate-700 hover:bg-slate-700 disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Vue</button><button data-ripple-light="true" class="inline-flex select-none items-center justify-center rounded-md rounded-l-none border border-l-0 border-slate-800 bg-slate-800 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-slate-50 transition-all duration-300 ease-in hover:border-slate-700 hover:bg-slate-700 disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Svelte</button></div>
  <div class="inline-flex flex-row"><button data-ripple-dark="true" class="inline-flex select-none items-center justify-center rounded-md rounded-r-none border border-slate-200 bg-slate-200 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-slate-800 transition-all duration-300 ease-in hover:bg-slate-100 hover:bg-slate-100 disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">React</button><button data-ripple-dark="true" class="inline-flex select-none items-center justify-center rounded-none border border-l-0 border-slate-200 bg-slate-200 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-slate-800 transition-all duration-300 ease-in hover:bg-slate-100 hover:bg-slate-100 disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Vue</button><button data-ripple-dark="true" class="inline-flex select-none items-center justify-center rounded-md rounded-l-none border border-l-0 border-slate-200 bg-slate-200 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-slate-800 transition-all duration-300 ease-in hover:bg-slate-100 hover:bg-slate-100 disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Svelte</button></div>
  <div class="inline-flex flex-row"><button data-ripple-light="true" class="inline-flex select-none items-center justify-center rounded-md rounded-r-none border border-blue-500 bg-blue-500 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-blue-50 transition-all duration-300 ease-in hover:border-info-light hover:bg-info-light disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">React</button><button data-ripple-light="true" class="inline-flex select-none items-center justify-center rounded-none border border-l-0 border-blue-500 bg-blue-500 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-blue-50 transition-all duration-300 ease-in hover:border-info-light hover:bg-info-light disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Vue</button><button data-ripple-light="true" class="inline-flex select-none items-center justify-center rounded-md rounded-l-none border border-l-0 border-blue-500 bg-blue-500 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-blue-50 transition-all duration-300 ease-in hover:border-info-light hover:bg-info-light disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Svelte</button></div>
  <div class="inline-flex flex-row "><button data-ripple-light="true" class="inline-flex select-none items-center justify-center rounded-md rounded-r-none border border-green-500 bg-green-500 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-green-50 transition-all duration-300 ease-in hover:border-success-light hover:bg-success-light disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">React</button><button data-ripple-light="true" class="inline-flex select-none items-center justify-center rounded-none border border-l-0 border-green-500 bg-green-500 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-green-50 transition-all duration-300 ease-in hover:border-success-light hover:bg-success-light disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Vue</button><button data-ripple-light="true" class="inline-flex select-none  items-center justify-center rounded-md rounded-l-none border border-l-0 border-green-500 bg-green-500 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-green-50 transition-all duration-300 ease-in hover:border-success-light hover:bg-success-light disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Svelte</button></div>
  <div class="inline-flex flex-row"><button data-ripple-light="true" class="inline-flex select-none items-center justify-center rounded-md rounded-r-none border border-amber-500 bg-amber-500 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-amber-50 transition-all duration-300 ease-in hover:border-warning-light hover:bg-warning-light disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">React</button><button data-ripple-light="true" class="inline-flex select-none items-center justify-center rounded-none border border-l-0 border-amber-500 bg-amber-500 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-amber-50 transition-all duration-300 ease-in hover:border-warning-light hover:bg-warning-light disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Vue</button><button data-ripple-light="true" class="inline-flex select-none  items-center justify-center rounded-md rounded-l-none border border-l-0 border-amber-500 bg-amber-500 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-amber-50 transition-all duration-300 ease-in hover:border-warning-light hover:bg-warning-light disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Svelte</button></div>
  <div class="inline-flex flex-row"><button data-ripple-light="true" class="inline-flex select-none items-center justify-center rounded-md rounded-r-none border border-red-500 bg-red-500 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-red-50 transition-all duration-300 ease-in hover:border-error-light hover:bg-error-light disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">React</button><button data-ripple-light="true" class="inline-flex select-none items-center justify-center rounded-none border border-l-0 border-red-500 bg-red-500 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-red-50 transition-all duration-300 ease-in hover:border-error-light hover:bg-error-light disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Vue</button><button data-ripple-light="true" class="inline-flex select-none items-center justify-center rounded-md rounded-l-none border border-l-0 border-red-500 bg-red-500 px-3.5 py-2.5 text-center align-middle font-sans text-sm font-medium leading-none text-red-50 transition-all duration-300 ease-in hover:border-error-light hover:bg-error-light disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none">Svelte</button></div>
</div>
`
      }}
    />
  );
}
