const buttonGradient = {
  "blue-grey": {
    backgroud: "bg-gradient-to-tr from-blue-grey-600 to-blue-grey-400",
    color: "text-white",
    shadow: "shadow-md shadow-blue-grey-100",
    hover: "hover:shadow-lg hover:shadow-blue-grey-200",
    active: "active:opacity-90",
  },
  grey: {
    backgroud: "bg-gradient-to-tr from-grey-600 to-grey-400",
    color: "text-white",
    shadow: "shadow-md shadow-grey-100",
    hover: "hover:shadow-lg hover:shadow-grey-200",
    active: "active:opacity-90",
  },
  brown: {
    backgroud: "bg-gradient-to-tr from-brown-600 to-brown-400",
    color: "text-white",
    shadow: "shadow-md shadow-brown-100",
    hover: "hover:shadow-lg hover:shadow-brown-200",
    active: "active:opacity-90",
  },
  "deep-orange": {
    backgroud: "bg-gradient-to-tr from-deep-orange-600 to-deep-orange-400",
    color: "text-white",
    shadow: "shadow-md shadow-deep-orange-100",
    hover: "hover:shadow-lg hover:shadow-deep-orange-200",
    active: "active:opacity-90",
  },
  orange: {
    backgroud: "bg-gradient-to-tr from-orange-600 to-orange-400",
    color: "text-white",
    shadow: "shadow-md shadow-orange-100",
    hover: "hover:shadow-lg hover:shadow-orange-200",
    active: "active:opacity-90",
  },
  amber: {
    backgroud: "bg-gradient-to-tr from-amber-600 to-amber-400",
    color: "text-black",
    shadow: "shadow-md shadow-amber-100",
    hover: "hover:shadow-lg hover:shadow-amber-200",
    active: "active:opacity-90",
  },
  yellow: {
    backgroud: "bg-gradient-to-tr from-yellow-600 to-yellow-400",
    color: "text-black",
    shadow: "shadow-md shadow-yellow-100",
    hover: "hover:shadow-lg hover:shadow-yellow-200",
    active: "active:opacity-90",
  },
  lime: {
    backgroud: "bg-gradient-to-tr from-lime-600 to-lime-400",
    color: "text-white",
    shadow: "shadow-md shadow-lime-100",
    hover: "hover:shadow-lg hover:shadow-lime-200",
    active: "active:opacity-90",
  },
  "light-green": {
    backgroud: "bg-gradient-to-tr from-light-green-600 to-light-green-400",
    color: "text-white",
    shadow: "shadow-md shadow-light-green-100",
    hover: "hover:shadow-lg hover:shadow-light-green-200",
    active: "active:opacity-90",
  },
  green: {
    backgroud: "bg-gradient-to-tr from-green-600 to-green-400",
    color: "text-white",
    shadow: "shadow-md shadow-green-100",
    hover: "hover:shadow-lg hover:shadow-green-200",
    active: "active:opacity-90",
  },
  teal: {
    backgroud: "bg-gradient-to-tr from-teal-600 to-teal-400",
    color: "text-white",
    shadow: "shadow-md shadow-teal-100",
    hover: "hover:shadow-lg hover:shadow-teal-200",
    active: "active:opacity-90",
  },
  cyan: {
    backgroud: "bg-gradient-to-tr from-cyan-600 to-cyan-400",
    color: "text-white",
    shadow: "shadow-md shadow-cyan-100",
    hover: "hover:shadow-lg hover:shadow-cyan-200",
    active: "active:opacity-90",
  },
  "light-blue": {
    backgroud: "bg-gradient-to-tr from-light-blue-600 to-light-blue-400",
    color: "text-white",
    shadow: "shadow-md shadow-light-blue-100",
    hover: "hover:shadow-lg hover:shadow-light-blue-200",
    active: "active:opacity-90",
  },
  blue: {
    backgroud: "bg-gradient-to-tr from-blue-600 to-blue-400",
    color: "text-white",
    shadow: "shadow-md shadow-blue-100",
    hover: "hover:shadow-lg hover:shadow-blue-200",
    active: "active:opacity-90",
  },
  indigo: {
    backgroud: "bg-gradient-to-tr from-indigo-600 to-indigo-400",
    color: "text-white",
    shadow: "shadow-md shadow-indigo-100",
    hover: "hover:shadow-lg hover:shadow-indigo-200",
    active: "active:opacity-90",
  },
  "deep-purple": {
    backgroud: "bg-gradient-to-tr from-deep-purple-600 to-deep-purple-400",
    color: "text-white",
    shadow: "shadow-md shadow-deep-purple-100",
    hover: "hover:shadow-lg hover:shadow-deep-purple-200",
    active: "active:opacity-90",
  },
  purple: {
    backgroud: "bg-gradient-to-tr from-purple-600 to-purple-400",
    color: "text-white",
    shadow: "shadow-md shadow-purple-100",
    hover: "hover:shadow-lg hover:shadow-purple-200",
    active: "active:opacity-90",
  },
  pink: {
    backgroud: "bg-gradient-to-tr from-pink-600 to-pink-400",
    color: "text-white",
    shadow: "shadow-md shadow-pink-100",
    hover: "hover:shadow-lg hover:shadow-pink-200",
    active: "active:opacity-90",
  },
  red: {
    backgroud: "bg-gradient-to-tr from-red-600 to-red-400",
    color: "text-white",
    shadow: "shadow-md shadow-red-100",
    hover: "hover:shadow-lg hover:shadow-red-200",
    active: "active:opacity-90",
  },
};

export default buttonGradient;
