const buttonFilled = {
  "blue-grey": {
    backgroud: "bg-blue-grey-500",
    color: "text-white",
    shadow: "shadow-md shadow-blue-grey-100",
    hover: "hover:shadow-lg hover:shadow-blue-grey-200",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  grey: {
    backgroud: "bg-grey-500",
    color: "text-white",
    shadow: "shadow-md shadow-grey-100",
    hover: "hover:shadow-lg hover:shadow-grey-200",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  brown: {
    backgroud: "bg-brown-500",
    color: "text-white",
    shadow: "shadow-md shadow-brown-100",
    hover: "hover:shadow-lg hover:shadow-brown-200",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  "deep-orange": {
    backgroud: "bg-deep-orange-500",
    color: "text-white",
    shadow: "shadow-md shadow-deep-orange-100",
    hover: "hover:shadow-lg hover:shadow-deep-orange-200",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  orange: {
    backgroud: "bg-orange-500",
    color: "text-white",
    shadow: "shadow-md shadow-orange-100",
    hover: "hover:shadow-lg hover:shadow-orange-200",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  amber: {
    backgroud: "bg-amber-500",
    color: "text-black",
    shadow: "shadow-md shadow-amber-100",
    hover: "hover:shadow-lg hover:shadow-amber-200",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  yellow: {
    backgroud: "bg-yellow-500",
    color: "text-black",
    shadow: "shadow-md shadow-yellow-100",
    hover: "hover:shadow-lg hover:shadow-yellow-200",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  lime: {
    backgroud: "bg-lime-500",
    color: "text-black",
    shadow: "shadow-md shadow-lime-100",
    hover: "hover:shadow-lg hover:shadow-lime-200",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  "light-green": {
    backgroud: "bg-light-green-500",
    color: "text-white",
    shadow: "shadow-md shadow-light-green-100",
    hover: "hover:shadow-lg hover:shadow-light-green-200",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  green: {
    backgroud: "bg-green-500",
    color: "text-white",
    shadow: "shadow-md shadow-green-100",
    hover: "hover:shadow-lg hover:shadow-green-200",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  teal: {
    backgroud: "bg-teal-500",
    color: "text-white",
    shadow: "shadow-md shadow-teal-100",
    hover: "hover:shadow-lg hover:shadow-teal-200",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  cyan: {
    backgroud: "bg-cyan-500",
    color: "text-white",
    shadow: "shadow-md shadow-cyan-100",
    hover: "hover:shadow-lg hover:shadow-cyan-200",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  "light-blue": {
    backgroud: "bg-light-blue-500",
    color: "text-white",
    shadow: "shadow-md shadow-light-blue-100",
    hover: "hover:shadow-lg hover:shadow-light-blue-200",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  blue: {
    backgroud: "bg-blue-500",
    color: "text-white",
    shadow: "shadow-md shadow-blue-100",
    hover: "hover:shadow-lg hover:shadow-blue-200",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  indigo: {
    backgroud: "bg-indigo-500",
    color: "text-white",
    shadow: "shadow-md shadow-indigo-100",
    hover: "hover:shadow-lg hover:shadow-indigo-200",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  "deep-purple": {
    backgroud: "bg-deep-purple-500",
    color: "text-white",
    shadow: "shadow-md shadow-deep-purple-100",
    hover: "hover:shadow-lg hover:shadow-deep-purple-200",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  purple: {
    backgroud: "bg-purple-500",
    color: "text-white",
    shadow: "shadow-md shadow-purple-100",
    hover: "hover:shadow-lg hover:shadow-purple-200",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  pink: {
    backgroud: "bg-pink-500",
    color: "text-white",
    shadow: "shadow-md shadow-pink-100",
    hover: "hover:shadow-lg hover:shadow-pink-200",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
  red: {
    backgroud: "bg-red-500",
    color: "text-white",
    shadow: "shadow-md shadow-red-100",
    hover: "hover:shadow-lg hover:shadow-red-200",
    focus: "focus:opacity-[0.85] focus:shadow-none",
    active: "active:opacity-[0.85] active:shadow-none",
  },
};

export default buttonFilled;
