export const buttonFilled = {
  "blue-grey": {
    backgroud: "bg-blue-gray-500",
    color: "text-white",
    shadow: "shadow-md shadow-blue-gray-500",
    hover: "hover:shadow-xl",
    focus: "focus:opacity-90 focus:shadow-none",
    active: "active:opacity-90 active:shadow-none",
  },
  grey: {
    backgroud: "bg-gray-500",
    color: "text-white",
    shadow: "shadow-md shadow-gray-500",
    hover: "hover:shadow-xl",
    focus: "focus:opacity-90 focus:shadow-none",
    active: "active:opacity-90 active:shadow-none",
  },
  brown: {
    backgroud: "bg-brown-500",
    color: "text-white",
    shadow: "shadow-md shadow-brown-500",
    hover: "hover:shadow-xl",
    focus: "focus:opacity-90 focus:shadow-none",
    active: "active:opacity-90 active:shadow-none",
  },
  "deep-orange": {
    backgroud: "bg-deep-orange-500",
    color: "text-white",
    shadow: "shadow-md shadow-deep-orange-500",
    hover: "hover:shadow-xl",
    focus: "focus:opacity-90 focus:shadow-none",
    active: "active:opacity-90 active:shadow-none",
  },
  orange: {
    backgroud: "bg-orange-500",
    color: "text-white",
    shadow: "shadow-md shadow-orange-500",
    hover: "hover:shadow-xl",
    focus: "focus:opacity-90 focus:shadow-none",
    active: "active:opacity-90 active:shadow-none",
  },
  amber: {
    backgroud: "bg-amber-500",
    color: "text-white",
    shadow: "shadow-md shadow-amber-500",
    hover: "hover:shadow-xl",
    focus: "focus:opacity-90 focus:shadow-none",
    active: "active:opacity-90 active:shadow-none",
  },
  yellow: {
    backgroud: "bg-yellow-500",
    color: "text-white",
    shadow: "shadow-md shadow-yellow-500",
    hover: "hover:shadow-xl",
    focus: "focus:opacity-90 focus:shadow-none",
    active: "active:opacity-90 active:shadow-none",
  },
  lime: {
    backgroud: "bg-lime-500",
    color: "text-white",
    shadow: "shadow-md shadow-lime-500",
    hover: "hover:shadow-xl",
    focus: "focus:opacity-90 focus:shadow-none",
    active: "active:opacity-90 active:shadow-none",
  },
  "light-green": {
    backgroud: "bg-light-green-500",
    color: "text-white",
    shadow: "shadow-md shadow-light-green-500",
    hover: "hover:shadow-xl",
    focus: "focus:opacity-90 focus:shadow-none",
    active: "active:opacity-90 active:shadow-none",
  },
  green: {
    backgroud: "bg-green-500",
    color: "text-white",
    shadow: "shadow-md shadow-green-500",
    hover: "hover:shadow-xl",
    focus: "focus:opacity-90 focus:shadow-none",
    active: "active:opacity-90 active:shadow-none",
  },
  teal: {
    backgroud: "bg-teal-500",
    color: "text-white",
    shadow: "shadow-md shadow-teal-500",
    hover: "hover:shadow-xl",
    focus: "focus:opacity-90 focus:shadow-none",
    active: "active:opacity-90 active:shadow-none",
  },
  cyan: {
    backgroud: "bg-cyan-500",
    color: "text-white",
    shadow: "shadow-md shadow-cyan-500",
    hover: "hover:shadow-xl",
    focus: "focus:opacity-90 focus:shadow-none",
    active: "active:opacity-90 active:shadow-none",
  },
  "light-blue": {
    backgroud: "bg-light-blue-500",
    color: "text-white",
    shadow: "shadow-md shadow-light-blue-500",
    hover: "hover:shadow-xl",
    focus: "focus:opacity-90 focus:shadow-none",
    active: "active:opacity-90 active:shadow-none",
  },
  blue: {
    backgroud: "bg-blue-500",
    color: "text-white",
    shadow: "shadow-md shadow-blue-500",
    hover: "hover:shadow-xl",
    focus: "focus:opacity-90 focus:shadow-none",
    active: "active:opacity-90 active:shadow-none",
  },
  indigo: {
    backgroud: "bg-indigo-500",
    color: "text-white",
    shadow: "shadow-md shadow-indigo-500",
    hover: "hover:shadow-xl",
    focus: "focus:opacity-90 focus:shadow-none",
    active: "active:opacity-90 active:shadow-none",
  },
  "deep-purple": {
    backgroud: "bg-deep-purple-500",
    color: "text-white",
    shadow: "shadow-md shadow-deep-purple-500",
    hover: "hover:shadow-xl",
    focus: "focus:opacity-90 focus:shadow-none",
    active: "active:opacity-90 active:shadow-none",
  },
  purple: {
    backgroud: "bg-purple-500",
    color: "text-white",
    shadow: "shadow-md shadow-purple-500",
    hover: "hover:shadow-xl",
    focus: "focus:opacity-90 focus:shadow-none",
    active: "active:opacity-90 active:shadow-none",
  },
  pink: {
    backgroud: "bg-pink-500",
    color: "text-white",
    shadow: "shadow-md shadow-pink-500",
    hover: "hover:shadow-xl",
    focus: "focus:opacity-90 focus:shadow-none",
    active: "active:opacity-90 active:shadow-none",
  },
  red: {
    backgroud: "bg-red-500",
    color: "text-white",
    shadow: "shadow-md shadow-red-500",
    hover: "hover:shadow-xl",
    focus: "focus:opacity-90 focus:shadow-none",
    active: "active:opacity-90 active:shadow-none",
  },
};

export default buttonFilled;
