export const buttonGradient = {
  "blue-grey": {
    backgroud: "bg-gradient-to-tr from-blue-grey-600 to-blue-grey-500",
    color: "text-white",
    shadow: "shadow-md shadow-blue-grey-500",
    hover: "hover:shadow-xl",
    focus: "",
    active: "active:opacity-90 active:shadow-lg",
  },
  grey: {
    backgroud: "bg-gradient-to-tr from-grey-600 to-grey-500",
    color: "text-white",
    shadow: "shadow-md shadow-grey-500",
    hover: "hover:shadow-xl",
    focus: "",
    active: "active:opacity-90 active:shadow-lg",
  },
  brown: {
    backgroud: "bg-gradient-to-tr from-brown-600 to-brown-500",
    color: "text-white",
    shadow: "shadow-md shadow-brown-500",
    hover: "hover:shadow-xl",
    focus: "",
    active: "active:opacity-90 active:shadow-lg",
  },
  "deep-orange": {
    backgroud: "bg-gradient-to-tr from-deep-orange-600 to-deep-orange-500",
    color: "text-white",
    shadow: "shadow-md shadow-deep-orange-500",
    hover: "hover:shadow-xl",
    focus: "",
    active: "active:opacity-90 active:shadow-lg",
  },
  orange: {
    backgroud: "bg-gradient-to-tr from-orange-600 to-orange-500",
    color: "text-white",
    shadow: "shadow-md shadow-orange-500",
    hover: "hover:shadow-xl",
    focus: "",
    active: "active:opacity-90 active:shadow-lg",
  },
  amber: {
    backgroud: "bg-gradient-to-tr from-amber-600 to-amber-500",
    color: "text-white",
    shadow: "shadow-md shadow-amber-500",
    hover: "hover:shadow-xl",
    focus: "",
    active: "active:opacity-90 active:shadow-lg",
  },
  yellow: {
    backgroud: "bg-gradient-to-tr from-yellow-600 to-yellow-500",
    color: "text-white",
    shadow: "shadow-md shadow-yellow-500",
    hover: "hover:shadow-xl",
    focus: "",
    active: "active:opacity-90 active:shadow-lg",
  },
  lime: {
    backgroud: "bg-gradient-to-tr from-lime-600 to-lime-500",
    color: "text-white",
    shadow: "shadow-md shadow-lime-500",
    hover: "hover:shadow-xl",
    focus: "",
    active: "active:opacity-90 active:shadow-lg",
  },
  "light-green": {
    backgroud: "bg-gradient-to-tr from-light-green-600 to-light-green-500",
    color: "text-white",
    shadow: "shadow-md shadow-light-green-500",
    hover: "hover:shadow-xl",
    focus: "",
    active: "active:opacity-90 active:shadow-lg",
  },
  green: {
    backgroud: "bg-gradient-to-tr from-green-600 to-green-500",
    color: "text-white",
    shadow: "shadow-md shadow-green-500",
    hover: "hover:shadow-xl",
    focus: "",
    active: "active:opacity-90 active:shadow-lg",
  },
  teal: {
    backgroud: "bg-gradient-to-tr from-teal-600 to-teal-500",
    color: "text-white",
    shadow: "shadow-md shadow-teal-500",
    hover: "hover:shadow-xl",
    focus: "",
    active: "active:opacity-90 active:shadow-lg",
  },
  cyan: {
    backgroud: "bg-gradient-to-tr from-cyan-600 to-cyan-500",
    color: "text-white",
    shadow: "shadow-md shadow-cyan-500",
    hover: "hover:shadow-xl",
    focus: "",
    active: "active:opacity-90 active:shadow-lg",
  },
  "light-blue": {
    backgroud: "bg-gradient-to-tr from-light-blue-600 to-light-blue-500",
    color: "text-white",
    shadow: "shadow-md shadow-light-blue-500",
    hover: "hover:shadow-xl",
    focus: "",
    active: "active:opacity-90 active:shadow-lg",
  },
  blue: {
    backgroud: "bg-gradient-to-tr from-blue-600 to-blue-500",
    color: "text-white",
    shadow: "shadow-md shadow-blue-500",
    hover: "hover:shadow-xl",
    focus: "",
    active: "active:opacity-90 active:shadow-lg",
  },
  indigo: {
    backgroud: "bg-gradient-to-tr from-indigo-600 to-indigo-500",
    color: "text-white",
    shadow: "shadow-md shadow-indigo-500",
    hover: "hover:shadow-xl",
    focus: "",
    active: "active:opacity-90 active:shadow-lg",
  },
  "deep-purple": {
    backgroud: "bg-gradient-to-tr from-deep-purple-600 to-deep-purple-500",
    color: "text-white",
    shadow: "shadow-md shadow-deep-purple-500",
    hover: "hover:shadow-xl",
    focus: "",
    active: "active:opacity-90 active:shadow-lg",
  },
  purple: {
    backgroud: "bg-gradient-to-tr from-purple-600 to-purple-500",
    color: "text-white",
    shadow: "shadow-md shadow-purple-500",
    hover: "hover:shadow-xl",
    focus: "",
    active: "active:opacity-90 active:shadow-lg",
  },
  pink: {
    backgroud: "bg-gradient-to-tr from-pink-600 to-pink-500",
    color: "text-white",
    shadow: "shadow-md shadow-pink-500",
    hover: "hover:shadow-xl",
    focus: "",
    active: "active:opacity-90 active:shadow-lg",
  },
  red: {
    backgroud: "bg-gradient-to-tr from-red-600 to-red-500",
    color: "text-white",
    shadow: "shadow-md shadow-red-500",
    hover: "hover:shadow-xl",
    focus: "",
    active: "active:opacity-90 active:shadow-lg",
  },
};

export default buttonGradient;
