

export default function InputColors() {
  return (
    <div
      dangerouslySetInnerHTML={{
        __html: `<div class="flex flex-col gap-4"><input placeholder="Input Primary" class="w-72 select-none rounded-md border border-slate-200 bg-transparent px-2.5 py-[8.5px] text-sm leading-none text-slate-800 outline-none ring ring-transparent transition-all duration-300 ease-in placeholder:text-slate-600/60 hover:border-slate-800 hover:ring-slate-800/10 focus:border-slate-800 focus:outline-none focus:ring-slate-800/10 dark:text-white" type="text" /><input placeholder="Input Secondary" class="w-72 select-none rounded-md border border-slate-200 bg-transparent px-2.5 py-[8.5px] text-sm leading-none text-slate-800 outline-none ring ring-transparent transition-all duration-300 ease-in placeholder:text-slate-600/60 hover:border-slate-500 hover:ring-secondary/10 focus:border-secondary focus:outline-none focus:ring-secondary/10 dark:text-white" type="text" /><input placeholder="Input Info" class="w-72 select-none rounded-md border border-slate-200 bg-transparent px-2.5 py-[8.5px] text-sm leading-none text-slate-800 outline-none ring ring-transparent transition-all duration-300 ease-in placeholder:text-slate-600/60 hover:border-info hover:ring-info/10 focus:border-info focus:outline-none focus:ring-info/10 dark:text-white" type="text" /><input placeholder="Input Success" class="w-72 select-none rounded-md border border-slate-200 bg-transparent px-2.5 py-[8.5px] text-sm leading-none text-slate-800 outline-none ring ring-transparent transition-all duration-300 ease-in placeholder:text-slate-600/60 hover:border-success hover:ring-success/10 focus:border-success focus:outline-none focus:ring-success/10 dark:text-white" type="text" /><input placeholder="Input Warning" class="w-72 select-none rounded-md border border-slate-200 bg-transparent px-2.5 py-[8.5px] text-sm leading-none text-slate-800 outline-none ring ring-transparent transition-all duration-300 ease-in placeholder:text-slate-600/60 hover:border-warning hover:ring-warning/10 focus:border-warning focus:outline-none focus:ring-warning/10 dark:text-white" type="text" /><input placeholder="Input Error" class="w-72 select-none rounded-md border border-slate-200 bg-transparent px-2.5 py-[8.5px] text-sm leading-none text-slate-800 outline-none ring ring-transparent transition-all duration-300 ease-in placeholder:text-slate-600/60 hover:border-error hover:ring-error/10 focus:border-error focus:outline-none focus:ring-error/10 dark:text-white" type="text" /></div>
`
      }}
    />
  );
}
