const buttonOutlined = {
  "blue-grey": {
    backgroud: "border border-blue-grey-500",
    color: "text-blue-grey-500",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-blue-grey-200",
    active: "active:opacity-[0.85]",
  },
  grey: {
    backgroud: "border border-grey-500",
    color: "text-grey-500",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-grey-200",
    active: "active:opacity-[0.85]",
  },
  brown: {
    backgroud: "border border-brown-500",
    color: "text-brown-500",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-brown-200",
    active: "active:opacity-[0.85]",
  },
  "deep-orange": {
    backgroud: "border border-deep-orange-500",
    color: "text-deep-orange-500",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-deep-orange-200",
    active: "active:opacity-[0.85]",
  },
  orange: {
    backgroud: "border border-orange-500",
    color: "text-orange-500",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-orange-200",
    active: "active:opacity-[0.85]",
  },
  amber: {
    backgroud: "border border-amber-500",
    color: "text-amber-500",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-amber-200",
    active: "active:opacity-[0.85]",
  },
  yellow: {
    backgroud: "border border-yellow-500",
    color: "text-yellow-500",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-yellow-200",
    active: "active:opacity-[0.85]",
  },
  lime: {
    backgroud: "border border-lime-500",
    color: "text-lime-500",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-lime-200",
    active: "active:opacity-[0.85]",
  },
  "light-green": {
    backgroud: "border border-light-green-500",
    color: "text-light-green-500",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-light-green-200",
    active: "active:opacity-[0.85]",
  },
  green: {
    backgroud: "border border-green-500",
    color: "text-green-500",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-green-200",
    active: "active:opacity-[0.85]",
  },
  teal: {
    backgroud: "border border-teal-500",
    color: "text-teal-500",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-teal-200",
    active: "active:opacity-[0.85]",
  },
  cyan: {
    backgroud: "border border-cyan-500",
    color: "text-cyan-500",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-cyan-200",
    active: "active:opacity-[0.85]",
  },
  "light-blue": {
    backgroud: "border border-light-blue-500",
    color: "text-light-blue-500",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-light-blue-200",
    active: "active:opacity-[0.85]",
  },
  blue: {
    backgroud: "border border-blue-500",
    color: "text-blue-500",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-blue-200",
    active: "active:opacity-[0.85]",
  },
  indigo: {
    backgroud: "border border-indigo-500",
    color: "text-indigo-500",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-indigo-200",
    active: "active:opacity-[0.85]",
  },
  "deep-purple": {
    backgroud: "border border-deep-purple-500",
    color: "text-deep-purple-500",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-deep-purple-200",
    active: "active:opacity-[0.85]",
  },
  purple: {
    backgroud: "border border-purple-500",
    color: "text-purple-500",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-purple-200",
    active: "active:opacity-[0.85]",
  },
  pink: {
    backgroud: "border border-pink-500",
    color: "text-pink-500",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-pink-200",
    active: "active:opacity-[0.85]",
  },
  red: {
    backgroud: "border border-red-500",
    color: "text-red-500",
    hover: "hover:opacity-75",
    focus: "focus:ring focus:ring-red-200",
    active: "active:opacity-[0.85]",
  },
};

export default buttonOutlined;
